### ISSUE TITLE
SVGO Options

### ISSUE THREAD

**Issue by timbomckay** [karify/external-svg-sprite-loader#57]
I've noticed you accept svgoOptions as a parameter but haven't seen any documentation. I'm currently running svgo locally before pushing to the repo with `svgo --disable=removeViewBox --enable=removeTitle` but not sure how I'd pass this to external-svg-sprite-loader.

Any guidance would be appreciated.

Thanks

**Comment by bensampaio** [comment]
You can just pass it to the loader:

```
options: {
  name: 'collection-1.svg',
  iconName: '[name]',
  svgoOptions: {
    plugins: [
      { removeViewBox: false },
      { removeTitle: true }
    ]
  }
}
```

You can find the default options in: https://github.com/karify/external-svg-sprite-loader/blob/d74e890eaaff9a6a2b1c28d680d069bf2ba4053c/lib/loader.js#L12. The default options are mandatory so that the loader works as expected so you'll need to copy them if you need to add more plugins.

I don't remove the title by default from the SVGs since that is discouraged for accessibility purposes.

**Comment by bensampaio** [comment]
By the way, SVGO is only used on the icons, there is currently no way to apply it on the sprite.

**Comment by timbomckay** [comment]
I'm assuming that's on build though right? It optimizes before building the sprite? That's my current flow. Sounds like it's the same.

**Comment by bensampaio** [comment]
Yes, it optimizes before building the sprite.
